## Write a Numpy program to compute the multiplication of two given matrixes

In [1]:
import numpy as np

In [18]:
 
a = ([2, 1, 5],[8 ,1, 8]) # 1st matrix
b = ([3, 2],[5, 7],[6, 1]) # 2nd matrix
 
np.dot(a,b) #mutiply (2,3)matrix & (3,2)matrix
 


array([[41, 16],
       [77, 31]])

## Write a NumPy program to compute the determinant of a given square array

In [23]:
from numpy import linalg as LA #import linalg method

arr=np.array([[5,8], [6, 3]]) #input array

print("Original array")
print(arr)
              
print("Determinant of the original array")
print(np.linalg.det(arr)) #built in fun to determinant

Original array
[[5 8]
 [6 3]]
Determinant of the original array
-33.0


## Write a NumPy program to compute the cross product of two given vectors

In [29]:
a= [[2, 6], [6, 8]]
b= [[1, 8], [2, 4]]

print("original matrix:")
print(a)
print(b)

res1 = np.cross(a, b) #built-in fun. of cross multiplication
res2 = np.cross(b, a)

print("cross product of the two vectors(a, b): ")
print(res1)

print("cross product of the two vectors(b, a): ")
print(res2)

original matrix:
[[2, 6], [6, 8]]
[[1, 8], [2, 4]]
cross product of the two vectors(a, b): 
[10  8]
cross product of the two vectors(b, a): 
[-10  -8]


## Write a NumPy program to compute the condition number of a given matrix

In [27]:
m = np.array([[1, 2, -5],
              [5, 1, 0],
              [1, 7, 2]])

print("Original matrix: ")
print(m)

print("The condition number of the orig. matrix: ")
print(LA.cond(a))

Original matrix: 
[[ 1  2 -5]
 [ 5  1  0]
 [ 1  7  2]]
The condition number of the orig. matrix: 
6.854101966249688


## Write a NumPy program to compute the inverse of a given matrix

In [28]:
n = np.array([[1,1],[6,8]])

print("Original matrix:")
print(n)

result =  np.linalg.inv(n)

print("Inverse of the matrix:")
print(result)


Original matrix:
[[1 1]
 [6 8]]
Inverse of the matrix:
[[ 4.  -0.5]
 [-3.   0.5]]
